### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by Xaxetrov** [Xaxetrov/OSCAR#2]
@anliec  You are the last person to have worked on this project. What is the status of TODOs in the README.md and the issue you opened ?

@frobion @gegeAi @br-g @Sn0wFox tagging you fyi.

**Comment by anliec** [comment]
Let say that some updating work as been done and pushed to Master, but it was in late August, it's probably outdated again now...
The big things is that the observation given by pysc2 as changed a lot if I remember correctly.
Lot of improvement can be done but I'm lacking time / motivation right now.

**Comment by Xaxetrov** [comment]
No problem. Just wanted to be sure that TODOs and issues are still relevant.

**Comment by anliec** [comment]
Look like issue #1 is not relevant anymore, I was using gym 0.10.5 at the time of the last commit and it looks like I fixed the code, I'm closing the issue.
